server:
  port: 8080

spring:
  datasource:
    username: root
    password: 1111
    url: jdbc:mysql://localhost:3306/aws_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug



## Redis 配置
redis:
  ## Redis数据库索引（默认为0）
  database: 0
  ## Redis服务器地址
  host: 192.168.126.129
  ## Redis服务器连接端口
  port: 6379
  ## Redis服务器连接密码（默认为空）
  password:
  jedis:
    pool:
      ## 连接池最大连接数（使用负值表示没有限制）
      #spring.redis.pool.max-active=8
      max-active: 8
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      #spring.redis.pool.max-wait=-1
      max-wait: -1
      ## 连接池中的最大空闲连接
      #spring.redis.pool.max-idle=8
      max-idle: 8
      ## 连接池中的最小空闲连接
      #spring.redis.pool.min-idle=0
      min-idle: 0
  ## 连接超时时间（毫秒）
  timeout: 1200

#将themilef的默认缓存禁用，热加载生效
thymeleaf:
  cache: false

#mybatis的下划线转驼峰配置
configuration:
  map-underscore-to-camel-case: true

  #另外一种打印语句的方式
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# pagehelper 配置
pagehelper:
  helperDialect: mysql
  reasonable: true #开启优化，<1页返回第一页
  supportMethodsArguments: true #是否支持接口参数来传递分页参数，默认false
  pageSizeZero: false #pageSize=0 返回所有
  params: count=countSql